uploaded_source: YAH_demo_export-20210525-075830.fst
use_template: no
surface_types: ~
subject_code: YAH
shiny_outputId: custom_3d_viewer-viewer_ready
project_name: '[Auto]'
main_camera: []
data_source_project: demo
data_source_pipeline_target: omnibus_results
data_source_pipeline: power_explorer/power_explorer-22_09_03-22_54_46
data_source: Uploads
controllers: []
