skip_coregistration: no
path_ct: rave-uploads/CT/YAH_CT.nii
dcm2niix_path: ''
params:
  nii_t1: MRI_RAW.nii
  nii_ct: CT_RAW.nii
  template_brain: ~
  dcm2niix:
    merge: Auto
    float: 'Yes'
    crop: 'No'
  segmentation:
    program: ants-preprocessing
  niftyreg:
    reference: T1-ants.nii.gz
    reg_type: rigid
    interp: trilinear
  ants:
    reference: T1-ants.nii.gz
    reg_type: Rigid
    aff_metric: mattes
    syn_metric: mattes
  flirt:
    reference: T1-ants.nii.gz
    dof: 6
    cost: mutualinfo
    search: 90
    searchcost: mutualinfo
  nipy:
    reference: T1-ants.nii.gz
    clean_source: yes
    inverse_target: yes
    precenter_source: yes
    reg_type: rigid
    similarity: crl1
    interp: pv
    optimizer: powell
  afni:
    reference: T1-ants.nii.gz
afni_path: /Users/dipterix/abin
skip_recon: no
path_mri: rave-uploads/MRI/MRI_RAW.nii
project_name: demo
freesurfer_path: /Applications/freesurfer/7.4.1
fsl_path: /usr/local/fsl
subject_code: YAH
