skip_validation: yes
import_setup__subject_code: PAV006
import_setup__project_name: test
import_channels__unit: NA
import_channels__sample_rate: 2000
import_channels__electrodes: 1-10
import_channels__electrode_file: auto
import_blocks__session_block: block003
import_blocks__format: Single BlackRock file (.nev+.nsx) per block
force_import: yes
